### ISSUE TITLE
the option `geoframe attach` doesn't work if variables already exist in the _shp file.  

### ISSUE THREAD

**Issue by asjadnaqvi** [benjann/geoplot#1]
When trying to combine files that I had cleaned up, it ran in the following problem.
![Screenshot 2023-05-17 143024](https://github.com/benjann/geoplot/assets/38498046/89a323cb-e076-4989-ace9-965718b2d537)

Here one can just "auto clean" shapefiles to contain just `_ID`, `_X`, `_Y`, `shape_order`.

**Comment by benjann** [comment]
I just posted an update that should solve this issue, I believe. `geoframe attach` no longer tries to add variables that already exist in the current frame.
