### ISSUE TITLE
Order when using colorpalettes

### ISSUE THREAD

**Issue by Monefield** [benjann/geoplot#15]
In my work I have to use specific colors in a specific order, so I have to use colorpalettes. I would like to use the colors in the order they are placed in the colorpalette (meaning that I always use the first X colors in the palette), but the reverse color-option seems to work differently than I would think when using colorpalettes. 
I have used your Italy-data for this small example:

* Categorizing pop98
gen pop98_cat3 = 1 if inrange(pop98,0,1000000)
replace pop98_cat3 = 2 if inrange(pop98,1000001,3000000)
replace pop98_cat3 = 3 if inrange(pop98,3000001,10000000)

label def pop98_cat3_lab 1 "Type 1" 2 "Type 2" 3 "Type 3", modify
label val pop98_cat3 pop98_cat3_lab

When I don't use a colorpalette the reverse color-option works like I would think it did (uses the same colors, but reverses their order):
**No reverse color-option - Right colors (1 2 3), wrong order (1 2 3)**
geoplot (area regions pop98_cat3, discrete) ///
, legend(reverse)
![Italy_colors_1](https://github.com/benjann/geoplot/assets/145358429/7281d004-de75-4cc3-b7c9-2164967a770c)

**Reverse color-option - Right colors (1 2 3), right order (3 2 1)**
geoplot (area regions pop98_cat3, discrete color(, reverse)) ///
, legend(reverse)
![Italy_colors_2](https://github.com/benjann/geoplot/assets/145358429/c91c3469-ed7e-436f-92cf-c115381c72c8)

Using colorpalettes combined with the reverse color-option reverses both the order, but also the colors:

**Colorpalette**
program colorpalette_colors_test
c_local P	#FF0000,	///	1 - Red
			#FF8000,	///	2 - Orange
			#FFFF00,	/// 3 - Yellow
			#00FF00,	/// 4 - Green
			#00FFFF,	/// 5 - Cyan
			#0000FF		//	6 - Blue
end
colorpalette colors_test

If I don't use the reverse color-option I get the right colors, but in the wrong order 
**Right colors (1 2 3), wrong order (1 2 3):**
geoplot (area regions pop98_cat3, discrete color(colors_test)) ///
, legend(reverse)
![Italy_colors_3](https://github.com/benjann/geoplot/assets/145358429/96d48ff8-17bc-45dc-a0da-27e6d21a39ca)

If I use the reverse color-option it reverses the palette as well 
**Wrong colors (4 5 6), wrong order (6 5 4):**
geoplot (area regions pop98_cat3, discrete color(colors_test, reverse)) ///
, legend(reverse)
![Italy_colors_4](https://github.com/benjann/geoplot/assets/145358429/1c8f9d61-3793-4cd0-813f-ff0a7aab9e39)

I found a possible workaround where I use only the appropriate subselection of the colorpalette 

**Right colors (1 2 3), right order (3 2 1):**
colorpalette colors_test, select(1 2 3) nograph
local colors_subselect `r(p)'

geoplot (area regions pop98_cat3, discrete color("`colors_subselect'", reverse)) ///
, legend(reverse)
![Italy_colors_5](https://github.com/benjann/geoplot/assets/145358429/17960f29-caa6-4f60-803d-d6751aae6668)

Since I've already found a workaround this is just wishfull thinking on my part, but it would be nice, that those two extra lines of code wasn't necessary :)

**Comment by benjann** [comment]
This is an issue related to `colorpalette`, not `geoplot`. The problem is that `colorpalette` does not know that this is a qualitative palette. Things work fine of you declare the palette as qualitative. That is, define the palette as:

```
program colorpalette_colors_test
    c_local P #FF0000, /// 1 - Red
              #FF8000, /// 2 - Orange
              #FFFF00, /// 3 - Yellow
              #00FF00, /// 4 - Green
              #00FFFF, /// 5 - Cyan
              #0000FF  //  6 - Blue
    c_local class qualitative
end
```

Alternatively, you could leave the palette definition as is and then type

```
geoplot (area regions pop98_cat3, discrete color(colors_test, class(qualitative) reverse))
```

or

```
geoplot (area regions pop98_cat3, discrete color(colors_test, select(1/3) reverse))
```

**Comment by Monefield** [comment]
That I didn't know! Very clever and nice with the alternative solutions! Thank you :)
