### ISSUE TITLE
Graph Inset On Maps

### ISSUE THREAD

**Issue by fahad-mirza** [benjann/geoplot#19]
Just wondering if there is a possibility to add insets onto maps where we can maybe add things like a histogram, line, bar plots etc. for chosen areas. Think of it as a zoom but instead of zooming a map we end up looking at other bits.

**Comment by benjann** [comment]
`geoplot` can do pie charts and bars; see layer types `pie` and `bar` in `help geoplot`.  But I guess this is not what you want.

Maybe try command [`grinset`](https://github.com/benjann/grinset). Type

```
ssc install grinset, replace
```

and then:

```
local url http://fmwww.bc.edu/repec/bocode/i/
geoframe create regions `url'Italy-RegionsData.dta, id(id) coord(xcoord ycoord) ///
    shpfile(Italy-RegionsCoordinates.dta)
geoplot (area regions fortell) (area regions), tight
grinset: twoway (scatter fortell relig3) (lfit fortell relig3) ///
    , title("fortell by relig3") legend(off) graphr(color(gs10))
```
![image](https://github.com/benjann/geoplot/assets/12543105/99af71f4-906c-4a70-825e-8622c59594e0)

See `help grinset` for info in how to manipulate size and position.

ben

**Comment by fahad-mirza** [comment]
Thank you ror this example! Looks nice. But i have a followup question. What if instead of zoom, we want to see histogram of the selected area or line chart etc. or am i over complicating this

**Comment by benjann** [comment]
Can you show me an example of what you have in mind? (e.g. from a published paper)

**Comment by fahad-mirza** [comment]
I can try looking for an example from a published paper but I was thinking something like this:
[https://www.esri.com/arcgis-blog/products/js-api-arcgis/mapping/make-your-histogram-legendary/](url)

Here they display a histogram as a legend but I was thinking like how trends, or distributions are looking like in a certain area / range on the map. I hope I am able to explain my idea properly.

**Comment by benjann** [comment]
ok, I see. I'm afraid my answer is the same as above. Draw your map using `geoplot`, then add a histogram or whatever plot you like using `grinset`. The map and the added plot can use different data sources, that is no problem. Simply load (or change frame to) the data for the added plot before applying `grinset`. Furthermore, you can apply `grinset` repeatedly to add multiple plots.

The details will depend on specific application.

**Comment by fahad-mirza** [comment]
Thanks for the detailed info
