### ISSUE TITLE
load main attribute layer as a default

### ISSUE THREAD

**Issue by asjadnaqvi** [benjann/geoplot#4]
When processing and merging the layers, by default, users end up at the shape layer in the "variables" window. While one can switch frames, a more intuitive thing would be to move to an attributes layer view. Maybe #2 can also resolve this with adding a `main` option:

`geoframe create <attribute_file> <shapefile>, [options id(_ID) setmain]` or something similar.

This would also allow users to add and merge layers in a second step once the frames are defined. Otherwise one really needs to prepare the data at fairly early stage. This gets a bit counter-intuitive from a workflow perspective. Additionally, a very likely use case scenario is that users work with a base layer, while other layers add added on as enhancements.

![image](https://github.com/benjann/geoplot/assets/38498046/2d27a830-b9ea-4a3b-af7e-6ad6593b56fc)

**Comment by benjann** [comment]
`geoframe create` now makes the created frame the current (working) frame; it also displays a description of the settings of the frame.

**Comment by asjadnaqvi** [comment]
Updated the scripts and works perfectly!
